source 'https://github.com/CocoaPods/Specs.git'

target 'AXToggleTitleContainerController', :exclusive => true do
  pod 'AXToggleTitleContainerController', :path => "../"
  pod 'FontAwesomeKit'
  pod 'LoremIpsum'
  pod 'SDWebImage'
end

target 'Tests', :exclusive => true do
  pod 'AXToggleTitleContainerController', :path => "../"
end
